# Generated by Django 4.2.5 on 2023-09-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_menuitem_item_menuitem_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='item',
            new_name='title',
        ),
    ]
